### ISSUE TITLE
Can't Install hassio-cli

### ISSUE THREAD

**Issue by MagicJF** [home-assistant/plugin-cli#104]
On a fresh Debian OS, in step 4 of [supervised-installer](https://github.com/home-assistant/supervised-installer):
when I execute the command
                 wget https://github.com/home-assistant/supervised-installer/releases/latest/download/homeassistant-supervised.deb
                 dpkg -i homeassistant-supervised.deb

I do get the following:
                Can't install ghcr.io/home-assistant/amd64-hassio-cli:**_2022.11.0_**
![imagen](https://user-images.githubusercontent.com/92638213/217958450-29785bed-06b0-41b0-81c6-26098a2d07d6.png)

Maybe it should, Instead, try to install ghcr.io/home-assistant/amd64-hassio-cli:**_2023.01.0_**  ??

**Comment by agners** [comment]
This was most likely caused by a (temporary) DNS lookup issue. Since this has been a while, I assume that this issue is no longer a problem.
